"""
This type stub file was generated by pyright.
"""

import sys
from arcade_accelerate import arcade_accelerate
from arcade_accelerate.module_patcher import AutoPopulatingDictionary, PatchingMetaPathFinder

def bootstrap() -> None: # -> None:
    ...

def patch_hitboxes(patches): # -> None:
    ...

def patch_spritelist_collision(patches): # -> None:
    ...

def patch_math(patches): # -> None:
    ...

def patch_geometry(patches): # -> None:
    ...

