"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import TypedDict
from pytiled_parser.parsers.json.properties import RawProperty, parse as parse_properties
from pytiled_parser.util import parse_color
from pytiled_parser.wang_set import WangColor, WangSet, WangTile

RawWangTile = TypedDict("RawWangTile", { "tileid": int,"wangid": List[int] })
RawWangColor = TypedDict("RawWangColor", { "color": str,"class": str,"name": str,"probability": float,"tile": int,"properties": List[RawProperty] })
RawWangSet = TypedDict("RawWangSet", { "colors": List[RawWangColor],"class": str,"name": str,"properties": List[RawProperty],"tile": int,"type": str,"wangtiles": List[RawWangTile] })
def parse(raw_wangset: RawWangSet) -> WangSet:
    """Parse the raw wangset into a pytiled_parser type

    Args:
        raw_wangset: Raw Wangset to be parsed.

    Returns:
        WangSet: A properly typed WangSet.
    """
    ...

