"""
This type stub file was generated by pyright.
"""

from imgui_bundle import imgui

class BaseOpenGLRenderer:
    def __init__(self) -> None:
        ...
    
    def render(self, draw_data):
        ...
    
    def refresh_font_texture(self):
        ...
    
    def shutdown(self): # -> None:
        ...
    


