def user_data_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, roaming: bool = False) -> str:
    ...

def site_data_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, multipath: bool = False) -> str:
    ...

def user_config_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, roaming: bool = False) -> str:
    ...

def site_config_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, multipath: bool = False) -> str:
    ...

def user_cache_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, opinion: bool = True) -> str:
    ...

def user_state_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, roaming: bool = False) -> str:
    ...

def user_log_dir(appname: str | None = None, appauthor: str | None = None, version: str | None = None, opinion: bool = True) -> str:
    ...