"""
This type stub file was generated by pyright.
"""

import shutil
import sys
import pyglet
import arcade
import PIL
from __future__ import annotations
from pathlib import Path

EXAMPLE_PATH = ...
def execute_from_command_line(): # -> None:
    ...

def show_info(): # -> None:
    ...

def start_project(path_str: str): # -> None:
    ...

