"""
This type stub file was generated by pyright.
"""

import pyglet
from typing import Dict, Optional
from pyglet.input import base
from pyglet.input.win32.directinput import DirectInputDevice, _create_controller, _di_manager as _di_device_manager, get_controllers as dinput_get_controllers, get_devices as dinput_get_devices, get_joysticks
from pyglet.input.win32.wintab import get_tablets
from pyglet.input.win32.xinput import XInputController, XInputControllerManager, XInputDevice, _device_manager as _xinput_device_manager, get_controllers as xinput_get_controllers, get_devices as xinput_get_devices

_xinput_enabled = ...
if not pyglet.options["win32_disable_xinput"]:
    _xinput_enabled = ...
if not _xinput_enabled:
    def xinput_get_devices(): # -> list[Any]:
        ...
    
    def xinput_get_controllers(): # -> list[Any]:
        ...
    
class Win32ControllerManager(base.ControllerManager):
    """This class manages XInput and DirectInput as a combined manager.
       XInput will override any XInput compatible DirectInput devices.
       Any devices not supported by XInput will fall back to DirectInput.
    """
    def __init__(self) -> None:
        ...
    
    def get_controllers(self): # -> list[Any]:
        ...
    


def get_devices(display=...): # -> list[Any]:
    ...

def get_controllers(display=...): # -> list[Any]:
    ...

