"""
This type stub file was generated by pyright.
"""

from .base import Config, Context, DisplayConfig
from pyglet.libs.win32.constants import *
from pyglet.libs.win32.types import *

class Win32Config(Config):
    def match(self, canvas): # -> list[Any] | list[Win32DisplayConfigARB] | list[Win32DisplayConfig]:
        ...
    


class Win32DisplayConfig(DisplayConfig):
    def __init__(self, canvas, pf, config) -> None:
        ...
    
    def create_context(self, share): # -> Win32Context:
        ...
    


class Win32DisplayConfigARB(DisplayConfig):
    attribute_ids = ...
    def __init__(self, canvas, pf, config) -> None:
        ...
    
    def create_context(self, share): # -> Win32ARBContext | Win32Context:
        ...
    


class _BaseWin32Context(Context):
    def __init__(self, config, share) -> None:
        ...
    
    def set_current(self): # -> None:
        ...
    
    def detach(self): # -> None:
        ...
    
    def flip(self): # -> None:
        ...
    
    def get_vsync(self): # -> bool | None:
        ...
    
    def set_vsync(self, vsync): # -> None:
        ...
    


class Win32Context(_BaseWin32Context):
    def attach(self, canvas): # -> None:
        ...
    


class Win32ARBContext(_BaseWin32Context):
    def attach(self, canvas): # -> None:
        ...
    


