"""
This type stub file was generated by pyright.
"""

from ctypes import *
from pyglet.gl.base import Config, Context, DisplayConfig

class XlibConfig(Config):
    def match(self, canvas): # -> list[Any] | list[XlibDisplayConfig]:
        ...
    


class XlibDisplayConfig(DisplayConfig):
    attribute_ids = ...
    def __init__(self, canvas, info, fbconfig, config) -> None:
        ...
    
    def get_visual_info(self): # -> Any:
        ...
    
    def create_context(self, share): # -> XlibContext:
        ...
    
    def is_complete(self): # -> Literal[True]:
        ...
    


class XlibContext(Context):
    def __init__(self, config, share) -> None:
        ...
    
    def is_direct(self): # -> Any:
        ...
    
    def attach(self, canvas): # -> None:
        ...
    
    def set_current(self): # -> None:
        ...
    
    def detach(self): # -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def set_vsync(self, vsync=...): # -> None:
        ...
    
    def get_vsync(self): # -> bool:
        ...
    
    def flip(self): # -> None:
        ...
    


