import PIL.Image
from arcade.types import AsFloat, Point2List, PointList, RGBA255
from arcade.types.rect import Rect
from arcade import Texture

__all__ = ["draw_arc_filled", "draw_arc_outline", "draw_parabola_filled", "draw_parabola_outline", "draw_circle_filled", "draw_circle_outline", "draw_ellipse_filled", "draw_ellipse_outline", "draw_line_strip", "draw_line", "draw_lines", "draw_point", "draw_points", "draw_polygon_filled", "draw_polygon_outline", "draw_triangle_filled", "draw_triangle_outline", "draw_lrbt_rectangle_outline", "draw_lbwh_rectangle_outline", "draw_rect_outline", "draw_lrbt_rectangle_filled", "draw_lbwh_rectangle_filled", "draw_rect_filled", "draw_rect_outline_kwargs", "draw_rect_filled_kwargs", "draw_scaled_texture_rectangle", "draw_texture_rectangle", "draw_lbwh_rectangle_textured", "get_pixel", "get_image"]

def draw_arc_filled(center_x: float, center_y: float, width: float, height: float, color: RGBA255, start_angle: float, end_angle: float, tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_arc_outline(center_x: float, center_y: float, width: float, height: float, color: RGBA255, start_angle: float, end_angle: float, border_width: float = ..., tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_parabola_filled(start_x: float, start_y: float, end_x: float, height: float, color: RGBA255, tilt_angle: float = ...) -> None: ...
def draw_parabola_outline(start_x: float, start_y: float, end_x: float, height: float, color: RGBA255, border_width: float = ..., tilt_angle: float = ...) -> None: ...
def draw_circle_filled(center_x: float, center_y: float, radius: float, color: RGBA255, tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_circle_outline(center_x: float, center_y: float, radius: float, color: RGBA255, border_width: float = ..., tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_ellipse_filled(center_x: float, center_y: float, width: float, height: float, color: RGBA255, tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_ellipse_outline(center_x: float, center_y: float, width: float, height: float, color: RGBA255, border_width: float = ..., tilt_angle: float = ..., num_segments: int = ...) -> None: ...
def draw_line_strip(point_list: PointList, color: RGBA255, line_width: float = ...) -> None: ...
def draw_line(start_x: float, start_y: float, end_x: float, end_y: float, color: RGBA255, line_width: float = ...) -> None: ...
def draw_lines(point_list: PointList, color: RGBA255, line_width: float = ...) -> None: ...
def draw_point(x: float, y: float, color: RGBA255, size: float) -> None: ...
def draw_points(point_list: PointList, color: RGBA255, size: float = ...) -> None: ...
def draw_polygon_filled(point_list: Point2List, color: RGBA255) -> None: ...
def draw_polygon_outline(point_list: Point2List, color: RGBA255, line_width: float = ...) -> None:...
def draw_triangle_filled(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, color: RGBA255) -> None: ...
def draw_triangle_outline(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, color: RGBA255, border_width: float = ...) -> None: ...
def draw_lrbt_rectangle_outline(left: float, right: float, bottom: float, top: float, color: RGBA255, border_width: float = ...) -> None: ...
def draw_lbwh_rectangle_outline(left: float, bottom: float, width: float, height: float, color: RGBA255, border_width: float = ...) -> None: ...
def draw_lrbt_rectangle_filled(left: float, right: float, bottom: float, top: float, color: RGBA255) -> None: ...
def draw_lbwh_rectangle_filled(left: float, bottom: float, width: float, height: float, color: RGBA255) -> None: ...
def draw_scaled_texture_rectangle(center_x: float, center_y: float, texture: Texture, scale: float = ..., angle: float = ..., alpha: int = ...) -> None: ...
def draw_texture_rectangle(center_x: float, center_y: float, width: float, height: float, texture: Texture, angle: float = ..., alpha: int = ...) -> None: ...
def draw_lbwh_rectangle_textured(left: float, bottom: float, width: float, height: float, texture: Texture, angle: float = ..., alpha: int = ...) -> None: ...
def draw_rect_outline(rect: Rect, color: RGBA255, border_width: float = ..., tilt_angle: float = ...) -> None: ...
def draw_rect_filled(rect: Rect, color: RGBA255, tilt_angle: float = ...) -> None: ...
def draw_rect_outline_kwargs(color: RGBA255 = ..., border_width: int = ..., tilt_angle: float = ..., **kwargs: AsFloat) -> None: ...
def draw_rect_filled_kwargs(color: RGBA255 = ..., tilt_angle: float = ..., **kwargs: AsFloat) -> None: ...
def get_pixel(x: int, y: int, components: int = ...) -> tuple[int, ...]: ...
def get_image(x: int = ..., y: int = ..., width: int | None = ..., height: int | None = ...) -> PIL.Image.Image: ...
