"""
This type stub file was generated by pyright.
"""

"""
Version

We are using a github action to bump the VERSION file versions.

2.7.3-dev.5
will go to:
2.7.3-dev.6

Problem is, python doesn't like that last period:
2.7.3-dev.5
should be
2.7.3.dev5
...and our github action doesn't like that pattern.
So this will delete that last period and flip around the dash.

ALSO note that this bumps the version AFTER the deploy.
So if we are at version 2.7.3.dev5 that's the version deploy. Bump will bump it to dev6.
"""
VERSION = ...
