"""
This type stub file was generated by pyright.
"""

from PIL.Image import Image
from arcade.types import Point2List
from .base import HitBoxAlgorithm

class SimpleHitBoxAlgorithm(HitBoxAlgorithm):
    """
    Simple hit box algorithm. This algorithm attempts to trim out transparent pixels
    from an image to create a hit box.
    """
    def calculate(self, image: Image, **kwargs) -> Point2List:
        """
        Given an RGBA image, this returns points that make up a hit box around it. Attempts
        to trim out transparent pixels.

        :param image:

        :Returns: List of points
        """
        ...
    


