"""
This type stub file was generated by pyright.
"""

import asyncio
import json
import os
import sys
import tempfile
import time
from .exceptions import PyPresenceException

"""Util functions that are needed but messy."""
def remove_none(d: dict): # -> dict[Any, Any]:
    ...

def get_ipc_path(pipe=...): # -> str | None:
    ...

def get_event_loop(force_fresh=...): # -> AbstractEventLoop | ProactorEventLoop:
    ...

create_task = ...
