"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional, TYPE_CHECKING, Union
from arcade.types import Point2List
from arcade import Texture

"""
A simple cache for hit boxes calculated from texture.
Hit box calculations are normally done at load time
by inspecting the contents of a loaded image.

Depending on the hit box algorithm a hit box is calculated:
* None     : Simply a box around the whole texture. No caching needed.
* Simple   : Scanning the corners for the texture
* Detailed : fairly detailed hit box generated by pymunk with detail parameter
"""
if TYPE_CHECKING:
    ...
class HitBoxCache:
    """
    A simple cache for hit box points for textures.

    These are calculated when loading a texture
    depending on the selected hit box algorithm.

    Points are stored as a tuple of xy points since
    it's important that they are immutable.
    """
    VERSION = ...
    def __init__(self) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self): # -> Iterator[str]:
        ...
    
    def get(self, name_or_texture: Union[str, Texture]) -> Optional[Point2List]:
        """
        Get the hit box points for a texture with a given hash
        and hit box algorithm.

        Example::

            # Get cached hit box for texture
            points = cache.get(texture)
            # Get a cache entry by string
            points = cache.get("hash|(0, 1, 2, 3)|simple|")

        :param keys: List of keys to use for the cache entry
        :param hit_box_algorithm: The hit box algorithm used
        """
        ...
    
    def put(self, name_or_texture: Union[str, Texture], points: Point2List) -> None:
        """
        Store hit box points for a texture.

        Example::

            # Cache hit box for texture
            cache.put(texture, points)
            # Cache with custom string
            cache.put("my_custom_points", points)

        :param keys: List of keys to use for the cache entry
        :param points: The hit box points
        """
        ...
    
    def load(self, path: Union[str, Path]) -> None:
        """
        Load a json file containing hit boxes.

        This adds the loaded hit boxes to the cache overwriting any existing
        entries and can therefore be called multiple times to populate it.

        if the file extension is ".gz" the file will be compressed.
        """
        ...
    
    def save(self, path: Path, indent: int = ...) -> None:
        """
        Save the hit box cache to disk.

        This can be used to pre-populate the cache to
        reduce the time it takes to load textures.

        if the file extension is ".gz" the file will be compressed.

        :param path: The path to save the cache to
        :param indent: The indentation level for the json file
        """
        ...
    
    def clear(self) -> None:
        """
        Clear the cache.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    


