"""
This type stub file was generated by pyright.
"""

from pyglet.media.drivers.base import AbstractAudioDriver, AbstractAudioPlayer
from pyglet.media.drivers.listener import AbstractListener

_debug = ...
class DirectSoundDriver(AbstractAudioDriver):
    def __init__(self) -> None:
        ...
    
    def create_audio_player(self, source, player): # -> DirectSoundAudioPlayer:
        ...
    
    def get_listener(self): # -> DirectSoundListener:
        ...
    
    def delete(self): # -> None:
        ...
    


class DirectSoundListener(AbstractListener):
    def __init__(self, ds_listener, ds_primary_buffer) -> None:
        ...
    


class DirectSoundAudioPlayer(AbstractAudioPlayer):
    def __init__(self, driver, source, player) -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    def play(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def get_play_cursor(self): # -> int:
        ...
    
    def work(self): # -> None:
        ...
    
    def set_volume(self, volume): # -> None:
        ...
    
    def set_position(self, position): # -> None:
        ...
    
    def set_min_distance(self, min_distance): # -> None:
        ...
    
    def set_max_distance(self, max_distance): # -> None:
        ...
    
    def set_pitch(self, pitch): # -> None:
        ...
    
    def set_cone_orientation(self, cone_orientation): # -> None:
        ...
    
    def set_cone_inner_angle(self, cone_inner_angle): # -> None:
        ...
    
    def set_cone_outer_angle(self, cone_outer_angle): # -> None:
        ...
    
    def set_cone_outer_gain(self, cone_outer_gain): # -> None:
        ...
    
    def prefill_audio(self): # -> None:
        ...
    


