"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from .particle import EternalParticle, FadeParticle, LifetimeParticle, Particle
from .emitter import EmitBurst, EmitController, EmitInterval, EmitMaintainCount, Emitter, EmitterIntervalWithCount, EmitterIntervalWithTime
from .emitter_simple import make_burst_emitter, make_interval_emitter

__all__ = ["Particle", "EternalParticle", "LifetimeParticle", "FadeParticle", "Emitter", "EmitController", "EmitBurst", "EmitMaintainCount", "EmitInterval", "EmitterIntervalWithCount", "EmitterIntervalWithTime", "make_burst_emitter", "make_interval_emitter"]
