"""
This type stub file was generated by pyright.
"""

from typing import Sequence
from arcade.types import PathOrTexture, Point
from .emitter import Emitter

"""
Convenience functions that provide a much simpler interface to Emitters and Particles.

These trade away some flexibility in favor of simplicity to allow beginners to start using particle systems.
"""
def make_burst_emitter(center_xy: Point, filenames_and_textures: Sequence[PathOrTexture], particle_count: int, particle_speed: float, particle_lifetime_min: float, particle_lifetime_max: float, particle_scale: float = ..., fade_particles: bool = ...) -> Emitter:
    """Returns an emitter that emits all of its particles at once"""
    ...

def make_interval_emitter(center_xy: Point, filenames_and_textures: Sequence[PathOrTexture], emit_interval: float, emit_duration: float, particle_speed: float, particle_lifetime_min: float, particle_lifetime_max: float, particle_scale: float = ..., fade_particles: bool = ...) -> Emitter:
    """Returns an emitter that emits its particles at a constant rate for a given amount of time"""
    ...

