"""
This type stub file was generated by pyright.
"""

from typing import Union

"""Prevents import issues.

If an :py:mod:`arcade.types` submodule attempts to run
``from arcade.types import AsFloat``, it could cause issues with
circular imports or partially initialized modules.
"""
AsFloat = Union[float, int]
__all__ = ['AsFloat']
