"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple, Optional, Tuple, TypedDict
from pyglet.math import Vec2
from arcade.types.numbers import AsFloat
from arcade.types.vector_like import Point2
from arcade.utils import ReplacementWarning, warning

"""Rects all act the same, but take four of the possible eight attributes and calculate the rest."""
RectParams = Tuple[AsFloat, AsFloat, AsFloat, AsFloat]
ViewportParams = Tuple[int, int, int, int]
class RectKwargs(TypedDict):
    """Annotates a plain :py:class:`dict` of :py:class:`Rect` arguments.

    This is only meaningful as a type annotation during type checking.
    For example, the :py:meth:`Rect.kwargs <arcade.types.Rect.kwargs>`
    property returns an ordinary will actually be a :py:class:`dict`
    of :py:class:`Rect` field names to :py:class:`float` values.

    To learn more, please see:

    * :py:class:`.Rect`
    * :py:class:`typing.TypedDict`

    """
    left: float
    right: float
    bottom: float
    top: float
    width: float
    height: float
    x: float
    y: float
    ...


class Rect(NamedTuple):
    """A rectangle, with several convenience properties and functions.

    This object is immutable by design. It provides no setters, and is a NamedTuple subclass.

    Attempts to implement all Rectangle functions used in the library, and to be a helpful
    tool for developers storing/maniulating rectangle and rectangle-like constructs.

    Rectangles cannot rotate by design, since this complicates their implmentation a lot.

    You probably don't want to create one of these directly, and should instead use a helper method, like
    :py:func:`.LBWH`, :py:func:`.LRBT`, :py:func:`.XYWH`, or :py:func:`.Viewport`.

    You can also use :py:meth:`.from_kwargs` to create a Rect from keyword arguments.

    """
    left: float
    right: float
    bottom: float
    top: float
    width: float
    height: float
    x: float
    y: float
    @property
    def center_x(self) -> float:
        """Backwards-compatible alias for :py:attr:`.x`."""
        ...
    
    @property
    def center_y(self) -> float:
        """Backwards-compatible alias for :py:attr:`.y`."""
        ...
    
    @property
    def center(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the center of the rectangle."""
        ...
    
    @property
    def bottom_left(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the bottom-left of the rectangle."""
        ...
    
    @property
    def bottom_right(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the bottom-right of the rectangle."""
        ...
    
    @property
    def top_left(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the top-left of the rectangle."""
        ...
    
    @property
    def top_right(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the top-right of the rectangle."""
        ...
    
    @property
    def bottom_center(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the bottom-center of the rectangle."""
        ...
    
    @property
    def center_right(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the center-right of the rectangle."""
        ...
    
    @property
    def top_center(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the top-center of the rectangle."""
        ...
    
    @property
    def center_left(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the center-left of the rectangle."""
        ...
    
    @property
    def size(self) -> Vec2:
        """Returns a :py:class:`~pyglet.math.Vec2` representing the size of the rectangle."""
        ...
    
    @property
    def area(self) -> float:
        """The area of the rectangle in square pixels."""
        ...
    
    @property
    def aspect_ratio(self) -> float:
        """Returns the ratio between the width and the height."""
        ...
    
    def at_position(self, position: Point2) -> Rect:
        """Returns a new :py:class:`Rect` which is moved to put `position` at its center."""
        ...
    
    def move(self, dx: AsFloat = ..., dy: AsFloat = ...) -> Rect:
        """
        Returns a new :py:class:`Rect` which is moved by `dx` in the
        x-direction and `dy` in the y-direction.
        """
        ...
    
    def resize(self, width: Optional[AsFloat] = ..., height: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """
        Returns a new :py:class:`Rect` at the current Rect's position,
        but with a new width and height, anchored at a point (default center.)
        """
        ...
    
    def scale(self, new_scale: AsFloat, anchor: Vec2 = ...) -> Rect:
        """
        Returns a new :py:class:`Rect` scaled by a factor of ``new_scale``,
        anchored at a point (default center.)
        """
        ...
    
    def scale_axes(self, new_scale: Point2, anchor: Vec2 = ...) -> Rect:
        """
        Return a new :py:class:`Rect`
        scaled by a factor of `new_scale.x` in the width
        and `new_scale.y` in the height, anchored at a point (default center.)
        """
        ...
    
    def __mul__(self, scale: AsFloat) -> Rect:
        """Scale the Rect by ``scale`` relative to ``(0, 0)``."""
        ...
    
    def __truediv__(self, scale: AsFloat) -> Rect:
        """Scale the rectangle by 1/``scale`` relative to ``(0, 0)``."""
        ...
    
    def align_top(self, value: AsFloat) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the top at `value`."""
        ...
    
    def align_bottom(self, value: AsFloat) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the bottom at `value`."""
        ...
    
    def align_left(self, value: AsFloat) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the left at `value`."""
        ...
    
    def align_right(self, value: AsFloat) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the right at `value`."""
        ...
    
    def align_center(self, value: Point2) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the center x and y at `value`."""
        ...
    
    def align_x(self, value: AsFloat) -> Rect:
        """Returns a new :py:class:`Rect`, which is aligned to the x at `value`."""
        ...
    
    @warning(ReplacementWarning, message=".align_center_x() is deprecated. Please use .align_x() instead.")
    def align_center_x(self, value: AsFloat) -> Rect:
        """Backwards-compatible alias for `Rect.x`."""
        ...
    
    def align_y(self, value: AsFloat) -> Rect:
        """Get a new :py:class:`Rect`, which is aligned to the y at `value`."""
        ...
    
    @warning(ReplacementWarning, message=".align_center_y() is deprecated. Please use .align_y() instead.")
    def align_center_y(self, value: AsFloat) -> Rect:
        """Backwards-compatible alias for `Rect.x`."""
        ...
    
    def min_size(self, width: Optional[AsFloat] = ..., height: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """
        Return a :py:class:`Rect` that is at least size `width` by `height`, positioned at
        the current position and anchored to a point (default center.)
        """
        ...
    
    def max_size(self, width: Optional[AsFloat] = ..., height: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """
        Return a :py:class:`Rect` that is at most size `width` by `height`, positioned at
        the current position and anchored to a point (default center.)
        """
        ...
    
    def clamp_height(self, min_height: Optional[AsFloat] = ..., max_height: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """
        Return a :py:class:`Rect` that has a height between `min_height` and `max_height`,
        positioned at the current position and anchored to a point (default center.)
        """
        ...
    
    def clamp_width(self, min_width: Optional[AsFloat] = ..., max_width: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """Return a :py:class:`.Rect` constrained to the passed dimension.

        It will be created as follows:

        * Its :py:attr:`.width` will be between any provided ``min_width``
          and ``max_width``
        * It will be positioned at the current position using the passed
          ``anchor``

        :param min_width: An optional minimum width.
        :param max_width: An optional maximum width.
        :param anchor: A :py:class:`~pyglet.math.Vec2` of the fractional
            percentage of the rectangle's total :py:attr:`.size` along
            both axes. It defaults to the center.
        """
        ...
    
    def clamp_size(self, min_width: Optional[AsFloat] = ..., max_width: Optional[AsFloat] = ..., min_height: Optional[AsFloat] = ..., max_height: Optional[AsFloat] = ..., anchor: Vec2 = ...) -> Rect:
        """Get a new clamped-size rectangle at the same position and anchored at ``anchor_point``.

        This combines the effects of :py:meth:`clamp_width` and :py:meth:`clamp_height` into
        one call.
        """
        ...
    
    def union(self, other: Rect) -> Rect:
        """Get the smallest rectangle covering both this one and ``other``."""
        ...
    
    def __or__(self, other: Rect) -> Rect:
        """Shorthand for :py:meth:`rect.union(other) <union>`.

        :param other: Another :py:class:`Rect` instance.
        """
        ...
    
    def intersection(self, other: Rect) -> Rect | None:
        """Return a :py:class:`Rect` of the overlap if any exists.

        If the two :py:class:`Rect` instances do not intersect, this
        method will return ``None`` instead.

        :param other: Another :py:class:`Rect` instance.
        """
        ...
    
    def __and__(self, other: Rect) -> Rect | None:
        """Shorthand for :py:meth:`rect.intersection(other) <interesection>`.

        :param other: Another :py:class:`Rect` instance.
        """
        ...
    
    def overlaps(self, other: Rect) -> bool:
        """Returns ``True`` if `other` overlaps with ``self``.

        :param other: Another :py:class:`Rect` instance.
        """
        ...
    
    def point_in_rect(self, point: Point2) -> bool:
        """Returns ``True`` if ``point`` is inside this rectangle.

        :param point: A tuple of :py:class:`int` or :py:class:`float` values.
        """
        ...
    
    def __contains__(self, point: Point2) -> bool:
        """Shorthand for :py:meth:`rect.point_in_rect(point) <point_in_rect>`.

        :param point: A tuple of :py:class:`int` or :py:class:`float` values.
        """
        ...
    
    def distance_from_bounds(self, point: Point2) -> float:
        """Returns the point's distance from the boundary of this rectangle."""
        ...
    
    def point_on_bounds(self, point: Point2, tolerance: float) -> bool:
        """Returns ``True`` if ``point`` is within ``tolerance`` of the bounds.

        The ``point``'s distance from the bounds is computed by through
        :py:meth:`distance_from_bounds`.

        :param point:
        """
        ...
    
    def position_to_uv(self, point: Point2) -> Vec2:
        """Convert a point to UV space values inside the rectangle.

        This is like a pair of ratios which measure how far the ``point``
        is from the rectangle's :py:meth:`bottom_left` up toward its
        :py:meth:`top_right` along each axis.

        .. warning:: This method does not clamp output!

                     Since ``point`` is absolute pixels, one or both axes
                     of the returned :py:class:`~pyglet.math.Vec2` can be:

                     * less than ``0.0``
                     * greater than ``1.0``


        Each axis of the return value measures how far into
        the rectangle's ``size`` the ``point`` is relative
        to the :py:meth:`bottom_left`:

        .. code-block:: python

           # consult the diagram below
           Vec2(
             (point.x - rect.left)   / rect.width,
             (point.y - rect.bottom) / rect.height
           )

        .. code-block::

              |------- rect.width ------|

                     The rectangle      (rect.top_right)
              +-------------------------T    ---
              |                         |     |
           - - - - - - - P  (Point x, y)|     |
           |  |                         | rect.height
           |  |          |              |     |
           y  |                         |     |
           |  B----------|--------------+    ---
           |  (rect.bottom_right)
           |
           O----- x -----|

        :param point: A point relative to the rectangle's
            :py:meth:`bottom_left` corner.

        """
        ...
    
    def uv_to_position(self, uv: Point2) -> Vec2:
        """Convert a point in UV-space to a point within the rectangle.

        The ``uv`` is a pair of ratios which describe how far a point
        extends across the rectangle's :py:attr:`width` and
        :py:attr:`height` from the :py:attr:`bottom_left` toward its
        :py:attr:`top_right`.

        .. warning:: This method does not clamp output!

                     Since one or both of ``uv``'s components can be
                     less than ``0.0`` or greater than ``1.0``, the
                     returned point can fall outside the rectangle.

        The following can be used as arguments to this function:

        #. Values in :py:class:`~arcade.types.AnchorPoint`
        #. Returned values from :py:meth:`position_to_uv`
        #. Rescaled input data from controllers

        :param uv: A pair of ratio values describing how far a
            a point falls from a rectangle's :py:attr:`bottom_left`
            toward its :py:attr:`top_right`.

        """
        ...
    
    def to_points(self) -> tuple[Vec2, Vec2, Vec2, Vec2]:
        """Return a new :py:class:`tuple` of this rectangle's corner points.

        The points will be ordered as follows:

        #. :py:meth:`bottom_left`
        #. :py:meth:`top_left`
        #. :py:meth:`top_right`
        #. :py:meth:`bottom_right`

        """
        ...
    
    @property
    def lbwh(self) -> RectParams:
        """Provides a tuple in the format of (left, bottom, width, height)."""
        ...
    
    @property
    def lrbt(self) -> RectParams:
        """Provides a tuple in the format of (left, right, bottom, top)."""
        ...
    
    @property
    def xywh(self) -> RectParams:
        """Provides a tuple in the format of (x, y, width, height)."""
        ...
    
    @property
    def xyrr(self) -> RectParams:
        """Provides a tuple in the format of (x, y, width / 2, height / 2)."""
        ...
    
    @property
    def viewport(self) -> ViewportParams:
        """Provides a tuple in the format of (left, bottom, width, height), coerced to integers."""
        ...
    
    @classmethod
    def from_kwargs(cls, **kwargs: AsFloat) -> Rect:
        """Creates a new Rect from keyword arguments. Throws ValueError if not enough are provided.

        Expected forms are:

        * LRBT (providing ``left``, ``right``, ``bottom``, and ``top``)
        * LBWH (providing ``left``, ``bottom``, ``width``, and ``height``)
        * XYWH (providing ``x``, ``y``, ``width``, and ``height``)
        """
        ...
    
    @property
    def kwargs(self) -> RectKwargs:
        """Get this rectangle as a :py:class:`dict` of field names to values.

        .. _tomli: https://github.com/hukkin/tomli

        Many data formats have corresponding Python modules with write
        support. Such modules often one or more functions which convert
        a passed :py:class:`dict` to a :py:class:`str` or write the result
        of such a conversion to a file.

        For example, the built-in :py:mod:`json` module offers the
        following functions on all Python versions currently supported
        by Arcade:

        .. list-table::
           :header-rows: 1

           * - Function
             - Summary
             - Useful For

           * - :py:func:`json.dump`
             - Write a :py:class:`dict` to a file
             - Saving game progress or edited levels

           * - :py:func:`json.dumps`
             - Get a :py:class:`dict` as a :py:class:`str` of JSON
             - Calls to a Web API

        .. note::

           The return value is an ordinary :py:class:`dict`.

           Although the return type is annotated as a
           :py:class:`.RectKwargs`, it is only meaningful when type
           checking. See :py:class:`typing.TypedDict` to learn more.

        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __bool__(self) -> bool:
        """Returns True if area is not 0, else False."""
        ...
    
    def __round__(self, n: int) -> Rect:
        """Rounds the left, right, bottom, and top to `n` decimals."""
        ...
    
    def __floor__(self) -> Rect:
        """Floors the left, right, bottom, and top."""
        ...
    
    def __ceil__(self) -> Rect:
        """Floors the left, right, bottom, and top."""
        ...
    


def LRBT(left: AsFloat, right: AsFloat, bottom: AsFloat, top: AsFloat) -> Rect:
    """Creates a new :py:class:`.Rect` from left, right, bottom, and top parameters."""
    ...

def LBWH(left: AsFloat, bottom: AsFloat, width: AsFloat, height: AsFloat) -> Rect:
    """Creates a new :py:class:`.Rect` from left, bottom, width, and height parameters."""
    ...

def XYWH(x: AsFloat, y: AsFloat, width: AsFloat, height: AsFloat, anchor: Vec2 = ...) -> Rect:
    """
    Creates a new :py:class:`.Rect` from x, y, width, and height parameters,
    anchored at a relative point (default center).
    """
    ...

def XYRR(x: AsFloat, y: AsFloat, half_width: AsFloat, half_height: AsFloat) -> Rect:
    """
    Creates a new :py:class:`.Rect` from center x, center y, half width, and half height parameters.
    This is mainly used by OpenGL.
    """
    ...

def Viewport(left: int, bottom: int, width: int, height: int) -> Rect:
    """Creates a new :py:class:`.Rect` from left, bottom, width, and height parameters, restricted to integers."""
    ...

__all__ = ['ViewportParams', 'RectParams', 'RectKwargs', 'Rect', 'AnchorPoint', 'LBWH', 'LRBT', 'XYWH', 'XYRR', 'Viewport']
