"""
This type stub file was generated by pyright.
"""

"""
See: https://www.shadertoy.com/view/lsBfRc
"""
class BloomFilter:
    """
    CRT Filter

    :param width:
    :param height:

    """
    def __init__(self, width: int, height: int, intensity: float) -> None:
        ...
    
    def use(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def draw(self, time: float = ..., target=...): # -> None:
        ...
    


