"""
This type stub file was generated by pyright.
"""

import arcade
from pathlib import Path
from typing import Union

"""
Simple video player with cv2.
This player can be improved a lot, but it does a decent job.

We simply read frames from cv2 and write them into
a texture.

Dependencies:
    pip install opencv-python
"""
class VideoPlayerCV2:
    """
    Primitive video player for arcade with cv2.
    Renders to the entire screen. Use VideoPlayer to render to specific coordinate.

    :param path: Path of the video that is to be played.
    """
    def __init__(self, path: Union[str, Path], loop: bool = ...) -> None:
        ...
    
    @property
    def width(self) -> int:
        """Video width."""
        ...
    
    @property
    def height(self) -> int:
        """Video height."""
        ...
    
    def draw(self) -> None:
        """Call this in `on_draw`."""
        ...
    
    def update(self, delta_time: float) -> None:
        """Move the frame forward."""
        ...
    


class CV2PlayerView(arcade.View):
    """
    A simple view to hold a video player using cv2.

    Requires the opencv-python module to be installed.

    :param path: Path of the video that is to be played.
    :param resize: Change the window size to the video size
    """
    def __init__(self, path: Union[str, Path], loop: bool = ..., resize: bool = ...) -> None:
        ...
    
    def on_draw(self) -> None:
        ...
    
    def on_update(self, delta_time: float) -> None:
        ...
    


if __name__ == '__main__':
    window = ...
