"""
This type stub file was generated by pyright.
"""

from arcade.types import Color, RGBA255
from arcade.types.rect import Rect
from .sprite import Sprite

class SpriteSolidColor(Sprite):
    """
    A rectangular sprite of the given ``width``, ``height``, and ``color``.

    The texture is automatically generated instead of loaded from a
    file. Internally only a single global texture is used for this
    sprite type, so concerns about memory usage non-existent regardless
    of size or number of sprite variations.

    :param width: Width of the sprite in pixels
    :param height: Height of the sprite in pixels
    :param center_x: Initial x position of the sprite
    :param center_y: Initial y position of the sprite
    :param color: The color of the sprite as a
        :py:class:`~arcade.types.Color`, an RGBA tuple, or an RGB
        tuple.
    :param angle: Initial angle of the sprite in degrees
    """
    __slots__ = ...
    _default_image = ...
    def __init__(self, width: int, height: int, center_x: float = ..., center_y: float = ..., color: RGBA255 = ..., angle: float = ..., **kwargs) -> None:
        ...
    
    @classmethod
    def from_rect(cls, rect: Rect, color: Color, angle: float = ...) -> SpriteSolidColor:
        """Construct a new SpriteSolidColor from a :py:class:`~arcade.types.rect.Rect`."""
        ...
    


class SpriteCircle(Sprite):
    """
    A circle of the specified `radius <https://simple.wikipedia.org/wiki/Radius>`_.

    The texture is automatically generated instead of loaded from a
    file.

    There may be a stutter the first time a combination of ``radius``,
    ``color``, and ``soft`` is used due to texture generation. All
    subsequent calls for the same combination will run faster because
    they will re-use the texture generated earlier.

    For a gradient fill instead of a solid color, set ``soft`` to
    ``True``. The circle will fade from an opaque center to transparent
    at the edges.

    :param radius: Radius of the circle in pixels
    :param color: The Color of the sprite as an RGB or RGBA tuple
    :param soft: If ``True``, the circle will fade from an opaque
                      center to transparent edges.
    """
    def __init__(self, radius: int, color: RGBA255, soft: bool = ..., **kwargs) -> None:
        ...
    


