"""
This type stub file was generated by pyright.
"""

class PyMunk:
    """Object used to hold pymunk info for a sprite."""
    __slots__ = ...
    def __init__(self) -> None:
        ...
    


class PymunkMixin:
    def __init__(self) -> None:
        ...
    
    def pymunk_moved(self, physics_engine, dx, dy, d_angle): # -> None:
        """Called by the pymunk physics engine if this sprite moves."""
        ...
    


