"""
This type stub file was generated by pyright.
"""

import logging

__all__ = ["debug", "info", "warn", "error", "critical", "log"]
def debug(message, **kwargs): # -> None:
    ...

def info(message, **kwargs): # -> None:
    ...

def warn(message, **kwargs): # -> None:
    ...

def error(message, **kwargs): # -> None:
    ...

def critical(message, **kwargs): # -> None:
    ...

def log(message, level=..., showtime=..., showprefix=...): # -> None:
    ...

class DigiFormatterHandler(logging.Handler):
    def __init__(self, *args, showsource=..., **kwargs) -> None:
        ...
    
    def emit(self, record): # -> None:
        ...
    


def getFreeLevel(base=...):
    ...

def addLogLevel(name, *args, base=..., **kwargs):
    ...

