"""
This type stub file was generated by pyright.
"""

__all__ = ["styles"]
class Style:
    __slots__ = ...
    def __init__(self, name, codes, prefix=..., showtime=..., showprefix=...) -> None:
        ...
    


class Styles:
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def create(self, name, *, fg=..., bg=..., attr=..., prefix=..., showtime=..., showprefix=...): # -> None:
        """Create a custom style"""
        ...
    
    def format(self, message, *, style=..., showtime=..., showprefix=...): # -> str:
        """Format a message in the requested style"""
        ...
    
    def print(self, *args, **kwargs): # -> None:
        """Print a message in the requested style"""
        ...
    
    def __getattr__(self, name): # -> Callable[..., None]:
        ...
    
    def __str__(self) -> str:
        ...
    


def getFirstNotNone(items): # -> None:
    ...

styles = ...
