"""
This type stub file was generated by pyright.
"""

from .codecs import Decoder, Encoder
from .api import dump, dumps, load, loads, reader, writer

__author__ = ...
__email__ = ...
__version__ = ...
