"""
This type stub file was generated by pyright.
"""

import json

class Decoder(json.JSONDecoder):
    def decode(self, s, *args, **kwargs): # -> Any:
        ...
    


class Encoder(json.JSONEncoder):
    def encode(self, obj, *args, **kwargs): # -> LiteralString:
        ...
    


