"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from .atlas_2d import AtlasRegion, TextureAtlas
from .base import TextureAtlasBase

__all__ = ['TextureAtlas', 'AtlasRegion', 'TextureAtlasBase']
