"""
This type stub file was generated by pyright.
"""

import abc
from typing import Optional, TYPE_CHECKING
from arcade import ArcadeContext, Texture
from arcade.texture import ImageData

"""
Texture Atlas for SpriteList

The long term goal is to rely on pyglet's texture atlas, but
it's still unclear what features we need supported in arcade
so need to prototype something to get started.

We're still building on pyglet's allocator.

Pyglet atlases are located here:
https://github.com/einarf/pyglet/blob/master/pyglet/image/atlas.py

Allocation:
Pyglet's allocator is a simple row based allocator only keeping
track of horizontal strips and how far in the x direction the
each strip is filled. We can't really "deallocate" unless it's
a region at the end of a strip and even doing that is awkward.

When an image is removed from the atlas we simply just lose that
region until we rebuild the atlas. It can be a good idea to count
the number of lost regions to use as an indicator later. When an
atlas is full we can first rebuild it if there are lost regions
instead of increasing the size.
"""
if TYPE_CHECKING:
    ...
RESIZE_STEP = ...
UV_TEXTURE_WIDTH = ...
LOG = ...
class ImageDataRefCounter:
    """
    Helper class to keep track of how many times an image is used
    by a texture in the atlas to determine when it's safe to remove it.

    Multiple Texture instances can and will use the same ImageData
    instance.
    """
    def __init__(self) -> None:
        ...
    
    def inc_ref(self, image_data: ImageData) -> None:
        """Increment the reference count for an image."""
        ...
    
    def dec_ref(self, image_data: ImageData) -> int:
        """
        Decrement the reference count for an image returning the new value.
        """
        ...
    
    def get_ref_count(self, image_data: ImageData) -> int:
        """
        Get the reference count for an image.

        Args:
            image_data (ImageData): The image to get the reference count for
        """
        ...
    
    def count_all_refs(self) -> int:
        """Helper function to count the total number of references."""
        ...
    
    def get_total_decref(self, reset=...) -> int:
        """
        Get the total number of decrefs.

        Args:
            reset (bool): Reset the counter after getting the value
        """
        ...
    
    def clear(self) -> None:
        """Clear the reference counter."""
        ...
    
    def __len__(self) -> int:
        ...
    
    def __repr__(self) -> str:
        ...
    


class TextureAtlasBase(abc.ABC):
    """Generic base for texture atlases."""
    def __init__(self, ctx: Optional[ArcadeContext]) -> None:
        ...
    
    @property
    def ctx(self) -> ArcadeContext:
        ...
    
    @abc.abstractmethod
    def remove(self, texture: Texture) -> None:
        """Remove a texture from the atlas."""
        ...
    


