"""
This type stub file was generated by pyright.
"""

from arcade.camera.grips.strafe import strafe
from arcade.camera.grips.rotate import rotate_around_forward, rotate_around_right, rotate_around_up
from arcade.camera.grips.screen_shake_2d import ScreenShake2D

__all__ = ("strafe", "rotate_around_right", "rotate_around_up", "rotate_around_forward", "ScreenShake2D")
