"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from arcade.camera.data_types import CameraData

__all__ = ("rotate_around_forward", "rotate_around_up", "rotate_around_right")
def rotate_around_forward(data: CameraData, angle: float) -> Tuple[float, float, float]:
    """
    Rotate the CameraData up vector around the CameraData forward vector, perfect for rotating the screen.
    This rotation will be around (0.0, 0.0) of the camera projection.
    If that is not the center of the screen this method may appear erroneous.
    Uses arcade.camera.controllers.quaternion_rotation internally.

    :param data: The camera data to modify. The data's up vector is rotated around its forward vector
    :param angle: The angle in degrees to rotate clockwise by
    """
    ...

def rotate_around_up(data: CameraData, angle: float) -> Tuple[float, float, float]:
    """
    Rotate the CameraData forward vector around the CameraData up vector.
    Generally only useful in 3D games.
    Uses arcade.camera.controllers.quaternion_rotation internally.

    :param data: The camera data to modify. The data's forward vector is rotated around its up vector
    :param angle: The angle in degrees to rotate clockwise by
    """
    ...

def rotate_around_right(data: CameraData, angle: float) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]:
    """
    Rotate both the CameraData's forward vector and up vector around a calculated right vector.
    Generally only useful in 3D games.
    Uses arcade.camera.controllers.quaternion_rotation internally.

    :param data: The camera data to modify. The data's forward vector is rotated around its up vector
    :param angle: The angle in degrees to rotate clockwise by
    """
    ...

