"""
This type stub file was generated by pyright.
"""

from arcade.camera.data_types import CameraData

"""
ScreenShakeController2D:
    Provides an easy way to cause a camera to shake.
"""
__all__ = ("ScreenShake2D", )
class ScreenShake2D:
    """
    Offsets the camera position in a random direction repeatedly over
    a set length of time to create a screen shake effect.

    The amplitude of the screen-shaking grows based on two functions.
    The first is a simple sin wave whose frequency is adjustable.
    This is multiplied with a pair of equations which go from 0-1 smoothly.
    the equation rises using a inverse exponential equation, before decreasing
    using a modified smooth-step sigmoid.

    Attributes:
        max_amplitude: The largest possible world space offset.
        falloff_duration: The length of time in seconds it takes the shaking
                          to reach 0 after reaching the maximum. Can be set
                          to a negative number to disable falloff.
        shake_frequency: The number of peaks per second. Avoid making it
                         a multiple of half the target frame-rate.
                         (e.g. at 60 fps avoid 30, 60, 90, 120, etc.)

    :param camera_data: The CameraData PoD that the controller modifies.
                        Should not be changed once initialized.
    :param max_amplitude: The largest possible world space offset.
    :param falloff_time: The length of time in seconds it takes the shaking
                        to reach 0 after reaching the maximum. Can be set
                        to a negative number to disable falloff.
    :param acceleration_duration: The length of time in seconds it takes the
                                shaking to reach max amplitude. Can be set
                                to 0.0 to start at max amplitude.
    :param shake_frequency: The number of peaks per second. Avoid making it
                            a multiple of half the target frame-rate.
                            (e.g. at 60 fps avoid 30, 60, 90, 120, etc.)
    """
    def __init__(self, camera_data: CameraData, *, max_amplitude: float = ..., falloff_time: float = ..., acceleration_duration: float = ..., shake_frequency: float = ...) -> None:
        ...
    
    @property
    def shaking(self) -> bool:
        """Read only property to check if the controller is currently shaking the camera."""
        ...
    
    @property
    def duration(self) -> float:
        """
        The length of the screen shake in seconds.

        If falloff is disabled (by setting falloff_duration to a negative number) only returns the
        acceleration duration.

        Setting the duration to a negative number disables falloff.
        While the falloff is disabled setting duration will only set the acceleration.
        Otherwise, scales both the acceleration and falloff time to match new duration.
        """
        ...
    
    @duration.setter
    def duration(self, _duration: float) -> None:
        ...
    
    @property
    def current_amplitude(self) -> float:
        """Read only property which provides the current shake amplitude."""
        ...
    
    @property
    def acceleration_duration(self) -> float:
        """
        The length of time in seconds it takes for the shaking to reach max amplitude.

        Setting to a value less than zero causes the amplitude to start at max.
        """
        ...
    
    @acceleration_duration.setter
    def acceleration_duration(self, _duration: float) -> None:
        ...
    
    @property
    def acceleration(self) -> float:
        """
        The inverse of acceleration time.

        setting to a value less than zero causes the amplitude to start at max.
        """
        ...
    
    @acceleration.setter
    def acceleration(self, _acceleration: float) -> None:
        ...
    
    @property
    def falloff(self) -> float:
        """
        The maximum gradient of the amplitude falloff,
        and is the gradient at the inflection point of the sigmoid equation.

        Is inversely proportional to the falloff duration by a factor of 15/8.
        """
        ...
    
    @falloff.setter
    def falloff(self, _falloff: float) -> None:
        ...
    
    def reset(self) -> None:
        """
        Reset the temporary shaking variables. WILL NOT STOP OR START SCREEN SHAKE.
        """
        ...
    
    def start(self) -> None:
        """
        Start the screen-shake.
        """
        ...
    
    def stop(self) -> None:
        """
        Instantly stop the screen-shake.
        """
        ...
    
    def update(self, delta_time: float) -> None:
        """
        Update the time, and decide if the shaking should stop.
        Does not actually set the camera position.
        Should not be called more than once an update cycle.

        :param delta_time: the length of time in seconds between update calls.
                        Generally pass in the delta_time provided by the
                        arcade.Window's on_update method.
        """
        ...
    
    def update_camera(self) -> None:
        """
        Update the position of the camera. Call this just before using the camera.
        because the controller is modifying the PoD directly it stores the last
        offset and resets the camera's position before adding the next offset.
        """
        ...
    
    def readjust_camera(self) -> None:
        """
        Can be called after the camera has been used revert the screen_shake.
        While not strictly necessary it is highly advisable. If you are moving the
        camera using an animation or something similar the behavior can start to go
        awry if you do not readjust after the screen shake.
        """
        ...
    


