"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from arcade.gl import Context

if TYPE_CHECKING:
    ...
class Query:
    """
    A query object to perform low level measurements of OpenGL rendering calls.

    The best way to create a program instance is through :py:meth:`arcade.gl.Context.query`

    Example usage::

        query = ctx.query()
        with query:
            geometry.render(..)

        print('samples_passed:', query.samples_passed)
        print('time_elapsed:', query.time_elapsed)
        print('primitives_generated:', query.primitives_generated)
    """
    __slots__ = ...
    def __init__(self, ctx: Context, samples=..., time=..., primitives=...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    @property
    def ctx(self) -> Context:
        """
        The context this query object belongs to

        :type: :py:class:`arcade.gl.Context`
        """
        ...
    
    @property
    def samples_passed(self) -> int:
        """
        How many samples was written. These are per component (RGBA)

        :type: int
        """
        ...
    
    @property
    def time_elapsed(self) -> int:
        """
        The time elapsed in nanoseconds

        :type: int
        """
        ...
    
    @property
    def primitives_generated(self) -> int:
        """
        How many primitives a vertex or geometry shader processed.
        When using a geometry shader this only counts
        the primitives actually emitted.

        :type: int
        """
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    def delete(self): # -> None:
        """
        Destroy the underlying OpenGL resource.
        Don't use this unless you know exactly what you are doing.
        """
        ...
    
    @staticmethod
    def delete_glo(ctx, glos) -> None:
        """
        Delete this query object. This is automatically called
        when the object is garbage collected.
        """
        ...
    


