"""
This type stub file was generated by pyright.
"""

from typing import Any, Tuple

def data_to_ctypes(data: Any) -> Tuple[int, Any]:
    """
    Attempts to convert the data to ctypes if needed by using the buffer protocol.

    Returns the byte size and the data.
    """
    ...

