"""
This type stub file was generated by pyright.
"""

import arcade.gl as gl
from __future__ import annotations
from typing import Optional, Tuple
from PIL import Image
from arcade import get_window
from arcade.resources import resolve
from arcade.experimental.background.background_texture import BackgroundTexture
from arcade.experimental.background.background import Background
from arcade.experimental.background.groups import BackgroundGroup, ParallaxGroup

__all__ = ["Background", "BackgroundGroup", "BackgroundTexture", "ParallaxGroup", "texture_from_file", "background_from_file"]
def texture_from_file(tex_src: str, offset: Tuple[float, float] = ..., scale: float = ..., angle: float = ..., filters=...) -> BackgroundTexture:
    ...

def background_from_file(tex_src: str, pos: Tuple[float, float] = ..., size: Optional[Tuple[int, int]] = ..., offset: Tuple[float, float] = ..., scale: float = ..., angle: float = ..., *, filters=..., color: Optional[Tuple[int, int, int]] = ..., color_norm: Optional[Tuple[float, float, float]] = ..., shader: Optional[gl.Program] = ..., geometry: Optional[gl.Geometry] = ...) -> Background:
    ...

