"""
This type stub file was generated by pyright.
"""

from typing import Optional
from arcade import Texture
from arcade.gui.events import UIOnChangeEvent, UIOnClickEvent
from arcade.gui.surface import Surface
from arcade.gui.widgets import UIInteractiveWidget

class UITextureToggle(UIInteractiveWidget):
    """
    A toggle button switching between on (True) and off (False) state.

    on_texture and off_texture are required.
    State dependent textures are generated by changing the brightness (hover, press)
    of the provided textures or converting them to grayscale (disabled).
    """
    value: bool = ...
    def __init__(self, *, x: float = ..., y: float = ..., width: float = ..., height: float = ..., on_texture: Optional[Texture] = ..., off_texture: Optional[Texture] = ..., value=..., size_hint=..., size_hint_min=..., size_hint_max=..., **kwargs) -> None:
        ...
    
    def on_click(self, event: UIOnClickEvent): # -> None:
        ...
    
    def do_render(self, surface: Surface): # -> None:
        ...
    
    def on_change(self, event: UIOnChangeEvent): # -> None:
        ...
    


