"""
This type stub file was generated by pyright.
"""

import pyglet
from .adaptation import OpenALDriver

_debug = pyglet.options['debug_media']
_debug_buffers = ...
def create_audio_driver(device_name=...): # -> OpenALDriver:
    ...

