"""
This type stub file was generated by pyright.
"""

import traceback
from imgui_bundle._imgui_bundle import imgui as imgui

def CHECK(result: bool) -> None:
    ...

def check_no_ret(result: bool) -> None:
    """
    Not implemented, because I did not understand the intended behavior

    #define IM_CHECK_OP(_LHS, _RHS, _OP, _RETURN)                       \
        do                                                              \
        {                                                               \
            ...                                                         \
            if (ImGuiTestEngine_Check(__FILE__, __func__, __LINE__, ImGuiTestCheckFlags_None, __res, expr_buf.c_str())) \
                IM_ASSERT(__res);                                       \
            if (_RETURN && !__res)                                      \
                return;                                                 \
        } while (0)
    """
    ...

