"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional, Union
from arcade.hitbox import HitBoxAlgorithm
from .texture import Texture
from . import SpriteSheet

class TextureManager:
    """
    This class is used to manage textures. It is used to keep track of
    textures that have been loaded, and to make sure we don't load the
    same texture twice.

    Textures loaded through this manager is cached internally.
    """
    def __init__(self) -> None:
        ...
    
    def texture(self, path: Union[str, Path], hit_box_algorithm: Optional[HitBoxAlgorithm] = ..., cache: bool = ...) -> Texture:
        """
        Loads a texture or returns a cached version.

        :param path: Path to the file to load.
        :param hit_box_algorithm: Algorithm to use to create a hit box for the texture.
        """
        ...
    
    def spritesheet(self, path: Union[str, Path], cache: bool = ...) -> SpriteSheet:
        """
        Loads a spritesheet or returns a cached version.

        :param path: Path to the file to load.
        :param cache: If ``True``, the spritesheet will be cached. If ``False``, the
            spite sheet will not be cached or returned from the cache.
        """
        ...
    
    def flush(self, sprite_sheets: bool = ..., textures: bool = ..., image_data: bool = ..., hit_boxes: bool = ...): # -> None:
        """
        Remove contents from the texture manager.

        :param sprite_sheets: If ``True``, sprite sheets will be flushed.
        :param textures: If ``True``, textures will be flushed.
        :param image_data: If ``True``, image data will be flushed.
        :param hit_boxes: If ``True``, hit boxes will be flushed.
        """
        ...
    


