"""
This type stub file was generated by pyright.
"""

from .texture import ImageData, Texture
from arcade.types import Size2D

_DEFAULT_TEXTURE = ...
_DEFAULT_IMAGE_SIZE = ...
def cleanup_texture_cache(): # -> None:
    """
    This cleans up the cache of textures. Useful when running unit tests so that
    the next test starts clean.
    """
    ...

def get_default_texture(size: Size2D[int] = ...) -> Texture:
    """
    Creates and returns a default texture and caches it internally for future use.

    :param size: Size of the texture to create
    :return: The default texture.
    """
    ...

def get_default_image(size: Size2D[int] = ...) -> ImageData:
    """
    Generates and returns a default image and caches it internally for future use.

    :param size: Size of the image to create.
    :return: The default image.
    """
    ...

if __name__ == "__main__":
    ...
